// Generated by ChoiceMaker. Do not edit.
package com.choicemaker.demo.simple_person_matching.gendata.gend.Person;
import java.util.Date;
import com.choicemaker.util.StringUtils;
/**
 * Generated base interface for the node type person. See package documentation for details.
 */
public interface IPersonRecordHolder extends com.choicemaker.cm.urm.base.IRecordHolder, PersonBase {}
