#
# Oracle
#
CREATE TABLE "CMT_STATUS_LOG" 
(
"JOB_ID" NUMBER(8) NOT NULL, 
"STATUS_ID" NUMBER(3) NOT NULL,
"INFO" VARCHAR2(256),
CONSTRAINT CMT_SL_PK PRIMARY KEY ("JOB_ID")
);



#
# SQL Server
#
CREATE TABLE "CMT_STATUS_LOG" 
(
"JOB_ID" NUMERIC(8) NOT NULL, 
"STATUS_ID" NUMERIC(3) NOT NULL,
"INFO" VARCHAR(256),
CONSTRAINT CMT_SL_PK PRIMARY KEY ("JOB_ID")
);



#
# DB2
#
CREATE TABLE "CMT_STATUS_LOG" 
(
"JOB_ID" INT NOT NULL, 
"STATUS_ID" SMALLINT NOT NULL,
"INFO" VARCHAR(256),
CONSTRAINT CMT_SL_PK PRIMARY KEY ("JOB_ID")
);
