#
# Oracle
#
CREATE TABLE "CMT_AUTONUMBER" 
(
"NAME" VARCHAR2(255) NOT NULL, 
"VALUE" NUMBER(10) NOT NULL,
CONSTRAINT PK_CMT_AUTONUMBER PRIMARY KEY ("NAME")
);


#
# SQL Server
#
CREATE TABLE "CMT_AUTONUMBER" 
(
"NAME" VARCHAR(255) NOT NULL, 
"VALUE" int NOT NULL,
CONSTRAINT PK_CMT_AUTONUMBER PRIMARY KEY ("NAME")
);


#
# DB2
#
CREATE TABLE "CMT_AUTONUMBER" 
(
"NAME" VARCHAR(255) NOT NULL, 
"VALUE" int NOT NULL,
CONSTRAINT PK_CMT_AUTONUMBER PRIMARY KEY ("NAME")
);


