// Generated by ChoiceMaker. Do not edit.
package com.choicemaker.demo.simple_person_matching.gendata.gend.Person;
import java.util.Date;
import com.choicemaker.util.StringUtils;
/**
 * Generated interface for the node type person. See package documentation for details.
 */
public interface Person extends PersonBase {
}
