// Generated by ChoiceMaker. Do not edit.
package com.choicemaker.demo.simple_person_matching.gendata.gend.internal.Person2;
import java.io.Serializable;
import com.choicemaker.cm.core.*;
import com.choicemaker.cm.core.base.*;
import com.choicemaker.cm.io.blocking.automated.base.*;
import com.choicemaker.demo.simple_person_matching.gendata.gend.internal.Person2.blocking.*;
import com.choicemaker.cm.core.blocking.*;
import com.choicemaker.cm.io.blocking.exact.base.*;
import com.choicemaker.cm.io.db.base.*;
import com.choicemaker.demo.simple_person_matching.gendata.gend.internal.Person2.db.*;
import com.choicemaker.cm.io.flatfile.base.*;
import com.choicemaker.demo.simple_person_matching.gendata.gend.internal.Person2.flatfile.*;
import com.choicemaker.cm.io.xml.base.*;
import com.choicemaker.demo.simple_person_matching.gendata.gend.internal.Person2.xml.*;
import com.choicemaker.cm.io.xml.base.*;
import com.choicemaker.cm.io.xml.base.*;
import com.choicemaker.demo.simple_person_matching.gendata.gend.Person2.*;
public class SimplePersonClues2Accessor implements java.io.Serializable, com.choicemaker.cm.core.Accessor{
public ClueSet getClueSet() {
return new SimplePersonClues2ClueSet();
}
public Descriptor getDescriptor() {
return PersonImpl____descriptor.instance;
}
public String getSchemaFileName() {
return "/Users/rphall/Documents/git/oscmt-cm/2.7.x/misc/mymojo-plugin-it/target/test-classes/smoke-test/src/main/cluemaker/Person2.schema";
}
public long getCreationDate() {
return 1405016596234L;
}
public int getNumRecordTypes() {
return 0;
}
public String getClueSetName() {
return "SimplePersonClues2";
}
public String getSchemaName() {
return "Person2";
}
private final DerivedSource BEAN_SOURCE = DerivedSource.valueOf("bean");
public Object toHolder(Record r) {
return new PersonHolder((PersonBase)r);
}
public Object toRecordHolder(Record r) {
return new PersonRecordHolder((PersonBase)r);
}
public Record toImpl(Object o) {
PersonImpl __res = new PersonImpl((PersonBase)o);
__res.computeValidityAndDerived(BEAN_SOURCE);
return __res;
}
public Object getBlockingConfiguration(String name, String dbConf) {
if("defaultAutomated".equals(name)) return new com.choicemaker.demo.simple_person_matching.gendata.gend.internal.Person2.blocking.Person2__defaultAutomated__BlockingConfiguration(dbConf);
return new com.choicemaker.demo.simple_person_matching.gendata.gend.internal.Person2.blocking.Person2__defaultAutomated__BlockingConfiguration(dbConf);
}
private static String[] blockingConfigurations = {"defaultAutomated"};
public String[] getBlockingConfigurations() {return blockingConfigurations;
}
public Object getExactInMemoryBlockingConfiguration(String name, Object pm) {
PositionMap positionMap = (PositionMap)pm;
return null;
}
private static String[] exactInMemoryBlockingConfigurations = {};
public String[] getExactInMemoryBlockingConfigurations() {return exactInMemoryBlockingConfigurations;
}
private static String[] dbConfigurations = {"default"};
public String[] getDbConfigurations() {return dbConfigurations;
}
public Object getDbReaderParallel(String name) {
if("default".equals(name)) return new com.choicemaker.demo.simple_person_matching.gendata.gend.internal.Person2.db.Person2__default__DbReaderParallel();
return new com.choicemaker.demo.simple_person_matching.gendata.gend.internal.Person2.db.Person2__default__DbReaderParallel();
}
public Object getDbReaderSequential(String name) {
if("default".equals(name)) return new com.choicemaker.demo.simple_person_matching.gendata.gend.internal.Person2.db.Person2__default__DbReaderSequential();
return new com.choicemaker.demo.simple_person_matching.gendata.gend.internal.Person2.db.Person2__default__DbReaderSequential();
}
public String[] getFlatFileFileNames() {
return flatFileFileNames;
}
private static final String[] flatFileFileNames = {"","person"};
private static int[] descWidths = {2, 10, 10, 6, 10, 32, 32, 32};
public int[] getDescWidths() {
return descWidths;
}
public Object getSingleFileFlatFileReader(Object tokenizer, boolean tagged, boolean singleLine) {
return new com.choicemaker.demo.simple_person_matching.gendata.gend.internal.Person2.flatfile.Person2SingleFileFlatFileReader((Tokenizer)tokenizer, tagged, singleLine);
}
public Object getMultiFileFlatFileReader(Object tokenizer, boolean tagged) {
return new com.choicemaker.demo.simple_person_matching.gendata.gend.internal.Person2.flatfile.Person2MultiFileFlatFileReader((Tokenizer[])tokenizer, tagged);
}
public Object getFlatFileRecordOutputter(boolean multiFile, boolean singleLine, boolean fixedLength, char sep, boolean tagged, int tagWidth, boolean filter) {
return new com.choicemaker.demo.simple_person_matching.gendata.gend.internal.Person2.flatfile.Person2FlatFileRecordOutputter(multiFile, singleLine, fixedLength, sep, tagged, tagWidth, filter);
}
public Object getXmlReader() {
return new com.choicemaker.demo.simple_person_matching.gendata.gend.internal.Person2.xml.Person2XmlReader();
}
private static transient Object xmlRecordOutputter = null;
public synchronized Object getXmlRecordOutputter() {
if(xmlRecordOutputter == null) {
xmlRecordOutputter = new com.choicemaker.demo.simple_person_matching.gendata.gend.internal.Person2.xml.Person2XmlRecordOutputter();
}
return xmlRecordOutputter;
}
private static transient Object reportOutputter = null;
public synchronized Object getReportOutputter() {
if(reportOutputter == null) {
reportOutputter = new com.choicemaker.demo.simple_person_matching.gendata.gend.internal.Person2.Person2XmlReporter();
}
return reportOutputter;
}
}
