CREATE TABLE CMT_OABA_BATCH_PARAMS (
 ID NUMERIC(19) NOT NULL,
 HIGH_THRESHOLD FLOAT(16) NULL,
 LOW_THRESHOLD FLOAT(16) NULL,
 MASTER_MODEL VARCHAR(255) NULL,
 MAX_SINGLE INTEGER NULL,
 STAGE_MODEL VARCHAR(255) NULL,
 PRIMARY KEY (ID)
);

INSERT INTO CMT_SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('OABA_BATCHPARAMS', 0);

