CREATE TABLE CMP_AUDIT (
 ID NUMERIC(19) NOT NULL,
 JOB_TYPE VARCHAR(31) NULL,
 EVENT VARCHAR(255) NULL,
 EVENT_DETAILS VARCHAR(255) NULL,
 EVENT_TYPE VARCHAR(255) NULL,
 TIMESTAMP DATETIME NULL,
 TRANSACTION_ID VARCHAR(255) NULL,
 JOB_ID NUMERIC(19) NULL,
 PRIMARY KEY (ID));

CREATE TABLE CMP_BATCH_JOB (
 ID NUMERIC(19) NOT NULL,
 JOB_TYPE VARCHAR(31) NULL,
 BatchJobStatus INTEGER NULL,
 DESCRIPTION VARCHAR(255) NULL,
 EXTERNAL_ID VARCHAR(255) NULL,
 FRACTION_COMPLETE INTEGER NULL,
 TRANSACTION_ID VARCHAR(255) NULL,
 TYPE VARCHAR(255) NULL,
 PRIMARY KEY (ID));

CREATE TABLE CMP_BATCH_PARAMS (
 ID NUMERIC(19) NOT NULL,
 HIGH_THRESHOLD FLOAT(16) NULL,
 LOW_THRESHOLD FLOAT(16) NULL,
 MASTER_MODEL VARCHAR(255) NULL,
 MAX_SINGLE INTEGER NULL,
 STAGE_MODEL VARCHAR(255) NULL,
 PRIMARY KEY (ID));

CREATE TABLE CMP_MODEL (
 ID NUMERIC(19) NOT NULL,
 CLUESET_NAME VARCHAR(255) NULL,
 CLUESET_SIGNATURE VARCHAR(255) NULL,
 EVALUATOR_SIGNATURE VARCHAR(255) NULL,
 ML_TYPE VARCHAR(255) NULL,
 MODEL_NAME VARCHAR(255) NULL,
 MODEL_SIGNATURE VARCHAR(255) NULL,
 SCHEMA_NAME VARCHAR(255) NULL,
 SCHEMA_SIGNATURE VARCHAR(255) NULL,
 PRIMARY KEY (ID));

CREATE TABLE CMP_STATUS_LOG (
 JOB_ID NUMERIC(19) NOT NULL,
 INFO VARCHAR(255) NULL,
 JOB_TYPE VARCHAR(255) NULL,
 STATUS_ID INTEGER NULL,
 VERSION INTEGER NULL,
 PRIMARY KEY (JOB_ID));

CREATE TABLE CMT_SEQUENCE (
 SEQ_NAME VARCHAR(50) NOT NULL,
 SEQ_COUNT NUMERIC(28) NULL,
 PRIMARY KEY (SEQ_NAME));

CREATE TABLE CM_MDB_MODEL_AUDIT (
 MODEL_ID NUMERIC(19) NULL,
 NOTE VARCHAR(255) NULL,
 TIMESTAMP DATETIME NULL);

CREATE TABLE CM_MDB_MODEL_FEATURE (
 CLUE_NUMBER INTEGER NULL,
 NAME VARCHAR(255) NULL,
 FEATURE_TYPE VARCHAR(255) NULL,
 ML_TYPE VARCHAR(255) NULL,
 WEIGHT FLOAT(16) NULL,
 MODEL_ID NUMERIC(19) NULL);

ALTER TABLE CMP_AUDIT ADD CONSTRAINT FK_CMP_AUDIT_JOB_ID FOREIGN KEY (JOB_ID) REFERENCES CMP_BATCH_JOB (ID);

ALTER TABLE CM_MDB_MODEL_AUDIT ADD CONSTRAINT CMMDBMODELAUDITMODELID FOREIGN KEY (MODEL_ID) REFERENCES CMP_MODEL (ID);

ALTER TABLE CM_MDB_MODEL_FEATURE ADD CONSTRAINT CMMDBMODELFEATUREMDLID FOREIGN KEY (MODEL_ID) REFERENCES CMP_MODEL (ID);

INSERT INTO CMT_SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('CMP_BATCHJOB', 0);

INSERT INTO CMT_SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('CMT_AUDIT', 0);

INSERT INTO CMT_SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('CMT_MODEL', 0);

