CREATE TABLE CM_MDB_MODEL (ID NUMERIC(19) NOT NULL,
 CLUESET_NAME VARCHAR(255) NULL,
 CLUESET_SIGNATURE VARCHAR(255) NULL,
 EVALUATOR_SIGNATURE VARCHAR(255) NULL,
 MODEL_NAME VARCHAR(255) NULL,
 MODEL_SIGNATURE VARCHAR(255) NULL,
 NOTES VARCHAR(255) NULL,
 SCHEMA_NAME VARCHAR(255) NULL,
 SCHEMA_SIGNATURE VARCHAR(255) NULL,
 PRIMARY KEY (ID)
);

INSERT INTO CMT_SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('CMT_MODEL', 0);

