CREATE TABLE CMT_OABA_BATCH_JOB (
 ID NUMERIC(19) NOT NULL,
 DESCRIPTION VARCHAR(255) NULL,
 EXTERNAL_ID VARCHAR(255) NULL,
 FRACTION_COMPLETE INTEGER NULL,
 STATUS INTEGER NULL,
 TRANSACTION_ID NUMERIC(19) NULL,
 TYPE VARCHAR(255) NULL,
 PRIMARY KEY (ID)
);	

CREATE TABLE SEQUENCE (
 SEQ_NAME VARCHAR(50) NOT NULL,
 SEQ_COUNT NUMERIC(28) NULL,
 PRIMARY KEY (SEQ_NAME)
);

INSERT INTO SEQUENCE(SEQ_NAME,SEQ_COUNT) values ('SEQ_GEN',0);
	
