#
# Oracle
#
CREATE TABLE "CMT_JOB_STATUS" 
(
"ID" NUMBER(8) NOT NULL, 
"EXTERNAL_ID" VARCHAR2(256),
"TRANSACTION_ID" NUMBER(8) NULL, 
"TYPE" VARCHAR2(256),
"DESCRIPTION" VARCHAR2(256),
"STATUS" VARCHAR2(25),
"FRACTION_COMPLETE" NUMBER(3),
"REQUESTED_TIMESTAMP" DATE,
"QUEUED_TIMESTAMP" DATE,
"STARTED_TIMESTAMP" DATE,
"UPDATED_TIMESTAMP" DATE,
"COMPLETED_TIMESTAMP" DATE,
"FAILED_TIMESTAMP" DATE,
"ABORT_REQUESTED_TIMESTAMP" DATE,
"ABORTED_TIMESTAMP" DATE,
CONSTRAINT CMT_JS_PK PRIMARY KEY ("ID")
);



#
# SQL Server
#
CREATE TABLE "CMT_JOB_STATUS" 
(
"ID" NUMERIC(8) NOT NULL, 
"EXTERNAL_ID" VARCHAR(256),
"TRANSACTION_ID" NUMERIC(8) NULL, 
"TYPE" VARCHAR(256),
"DESCRIPTION" VARCHAR(256),
"STATUS" VARCHAR(25),
"FRACTION_COMPLETE" NUMERIC(3),
"REQUESTED_TIMESTAMP" DATETIME,
"QUEUED_TIMESTAMP" DATETIME,
"STARTED_TIMESTAMP" DATETIME,
"UPDATED_TIMESTAMP" DATETIME,
"COMPLETED_TIMESTAMP" DATETIME,
"FAILED_TIMESTAMP" DATETIME,
"ABORT_REQUESTED_TIMESTAMP" DATETIME,
"ABORTED_TIMESTAMP" DATETIME,
CONSTRAINT CMT_JS_PK PRIMARY KEY ("ID")
);



#
# DB2
#
CREATE TABLE "CMT_JOB_STATUS" 
(
"ID" INT NOT NULL, 
"EXTERNAL_ID" VARCHAR(256),
"TRANSACTION_ID" INT NULL, 
"TYPE" VARCHAR(256),
"DESCRIPTION" VARCHAR(256),
"STATUS" VARCHAR(25),
"FRACTION_COMPLETE" INT,
"REQUESTED_TIMESTAMP" TIMESTAMP,
"QUEUED_TIMESTAMP" TIMESTAMP,
"STARTED_TIMESTAMP" TIMESTAMP,
"UPDATED_TIMESTAMP" TIMESTAMP,
"COMPLETED_TIMESTAMP" TIMESTAMP,
"FAILED_TIMESTAMP" TIMESTAMP,
"ABORT_REQUESTED_TIMESTAMP" TIMESTAMP,
"ABORTED_TIMESTAMP" TIMESTAMP,
CONSTRAINT CMT_JS_PK PRIMARY KEY ("ID")
);
