// Generated by ChoiceMaker. Do not edit.
package com.choicemaker.demo.simple_person_matching.gendata.gend.internal.Person2.xml;
import org.apache.log4j.*;
import java.util.*;
import org.xml.sax.*;
import org.xml.sax.helpers.*;
import com.choicemaker.cm.core.*;
import com.choicemaker.cm.core.base.*;
import com.choicemaker.cm.io.xml.base.*;
import com.choicemaker.cm.core.util.*;
import com.choicemaker.util.*;
import com.choicemaker.demo.simple_person_matching.gendata.gend.internal.Person2.*;
import java.util.Date;
import com.choicemaker.util.StringUtils;
import com.choicemaker.cm.validation.eclipse.impl.Validators;
public final class Person2XmlReader extends XmlReader {
private static Logger logger = Logger.getLogger(com.choicemaker.demo.simple_person_matching.gendata.gend.internal.Person2.xml.Person2XmlReader.class);
private int[] typeStack = new int[5];
private int top = 0;
private int unknown = 0;
private LinkedList l__PersonImpl = new LinkedList();
private PersonImpl o__PersonImpl;
private RecordHandler rh;
private static DerivedSource src = DerivedSource.valueOf("xml");
public void open(RecordHandler rh) {
this.rh = rh;
typeStack[top] = -1;
}
public void startElement (String uri, String localName, String qName, Attributes atts) throws SAXException {
String __tmpStr;
if(unknown > 0) {
++unknown;
} else {
String elementName = qName.intern();
switch(typeStack[top]) {
case -1:
if(elementName == "person") {
typeStack[++top] = 0;
o__PersonImpl = new PersonImpl();
int len = atts.getLength();
for(int i = 0; i < len; ++i) {
String attributeName = atts.getQName(i).intern();
if(attributeName == "linkage_role") {
o__PersonImpl.linkage_role = atts.getValue(i);
} else if(attributeName == "entityId") {
o__PersonImpl.entityId = atts.getValue(i).length() == 0 ? (int)0 : Integer.parseInt(atts.getValue(i));
} else if(attributeName == "recordId") {
o__PersonImpl.recordId = atts.getValue(i).length() == 0 ? (int)0 : Integer.parseInt(atts.getValue(i));
} else if(attributeName == "ssn") {
o__PersonImpl.ssn = atts.getValue(i);
} else if(attributeName == "firstName") {
o__PersonImpl.firstName = atts.getValue(i);
} else if(attributeName == "middleName") {
o__PersonImpl.middleName = atts.getValue(i);
} else if(attributeName == "lastName") {
o__PersonImpl.lastName = atts.getValue(i);
} else if(attributeName == "streetNumber") {
o__PersonImpl.streetNumber = atts.getValue(i);
} else if(attributeName == "streetName") {
o__PersonImpl.streetName = atts.getValue(i);
} else if(attributeName == "apartmentNumber") {
o__PersonImpl.apartmentNumber = atts.getValue(i);
} else if(attributeName == "city") {
o__PersonImpl.city = atts.getValue(i);
} else if(attributeName == "state") {
o__PersonImpl.state = atts.getValue(i);
} else if(attributeName == "zip") {
o__PersonImpl.zip = atts.getValue(i);
} else {
}
}
} else {
++unknown;
}
break;
}
}
}
public void endElement (String uri, String localName, String qName) throws SAXException {
if(unknown > 0) {
--unknown;
} else {
switch(typeStack[top]) {
case 0:
break;
}
--top;
if(top == 0) {
o__PersonImpl.computeValidityAndDerived(src);
rh.handleRecord(o__PersonImpl);
}
}
}
}
