CREATE TABLE CMT_TRANSITIVITY_JOB (
 ID NUMERIC(19) NOT NULL,
 DESCRIPTION VARCHAR(255) NULL,
 DIFFER FLOAT(16) NULL,
 MATCH FLOAT(16) NULL,
 MODEL VARCHAR(255) NULL,
 FRACTION_COMPLETE INTEGER NULL,
 STATUS INTEGER NULL,
 PRIMARY KEY (ID)
);

CREATE TABLE CMT_TRANSITIVITYJOB_TIMESTAMPS (
 TRANSITIVITYJOB_ID NUMERIC(19) NULL,
 TIMESTAMP DATETIME NULL,
 STATUS INTEGER NULL
);

ALTER TABLE CMT_TRANSITIVITYJOB_TIMESTAMPS
 ADD CONSTRAINT CMTTRNSTVTYTRNSTVTYJBD
  FOREIGN KEY (TRANSITIVITYJOB_ID) REFERENCES CMT_TRANSITIVITY_JOB (ID)

INSERT INTO CMT_SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('TRANSITIVITYJOB', 0)

