CREATE TABLE CMT_OABA_BATCHJOB (
 ID NUMERIC(19) NOT NULL,
 DESCRIPTION VARCHAR(255) NULL,
 EXTERNAL_ID VARCHAR(255) NULL,
 FRACTION_COMPLETE INTEGER NULL,
 STATUS INTEGER NULL,
 TRANSACTION_ID NUMERIC(19) NULL,
 TYPE VARCHAR(255) NULL,
 PRIMARY KEY (ID)
);

CREATE TABLE CMT_OABA_BATCHJOB_AUDIT (
 BATCHJOB_ID NUMERIC(19) NULL,
 STATUS VARCHAR(255) NULL,
 TIMESTAMP DATETIME NULL
);

CREATE TABLE CMT_OABA_BATCH_PARAMS (
 ID NUMERIC(19) NOT NULL,
 HIGH_THRESHOLD FLOAT(16) NULL,
 LOW_THRESHOLD FLOAT(16) NULL,
 MASTER_MODEL VARCHAR(255) NULL,
 MAX_SINGLE INTEGER NULL,
 STAGE_MODEL VARCHAR(255) NULL,
 PRIMARY KEY (ID)
);

CREATE TABLE CMT_OABA_STATUS_LOG (
 JOB_ID NUMERIC(19) NOT NULL,
 INFO VARCHAR(255) NULL,
 JOB_TYPE VARCHAR(255) NULL,
 STATUS_ID INTEGER NULL,
 VERSION INTEGER NULL,
 PRIMARY KEY (JOB_ID)
);

CREATE TABLE CMT_SEQUENCE (
 SEQ_NAME VARCHAR(50) NOT NULL,
 SEQ_COUNT NUMERIC(28) NULL,
 PRIMARY KEY (SEQ_NAME)
);

CREATE TABLE CMT_TRANSITIVITY_JOB (
 ID NUMERIC(19) NOT NULL,
 DESCRIPTION VARCHAR(255) NULL,
 DIFFER FLOAT(16) NULL,
 MATCH FLOAT(16) NULL,
 MODEL VARCHAR(255) NULL,
 FRACTION_COMPLETE INTEGER NULL,
 STATUS INTEGER NULL,
 PRIMARY KEY (ID)
);

CREATE TABLE CMT_TRANSITIVITYJOB_AUDIT (
 TRANSITIVITYJOB_ID NUMERIC(19) NULL,
 TIMESTAMP DATETIME NULL,
 STATUS INTEGER NULL
);

CREATE TABLE CM_MDB_MODEL (
 ID NUMERIC(19) NOT NULL,
 CLUESET_NAME VARCHAR(255) NULL,
 CLUESET_SIGNATURE VARCHAR(255) NULL,
 EVALUATOR_SIGNATURE VARCHAR(255) NULL,
 ML_TYPE VARCHAR(255) NULL,
 MODEL_NAME VARCHAR(255) NULL,
 MODEL_SIGNATURE VARCHAR(255) NULL,
 SCHEMA_NAME VARCHAR(255) NULL,
 SCHEMA_SIGNATURE VARCHAR(255) NULL,
 PRIMARY KEY (ID)
);

CREATE TABLE CM_MDB_MODEL_FEATURE (
 CLUE_NUMBER INTEGER NULL,
 NAME VARCHAR(255) NULL,
 FEATURE_TYPE VARCHAR(255) NULL,
 ML_TYPE VARCHAR(255) NULL,
 WEIGHT FLOAT(16) NULL,
 MODEL_ID NUMERIC(19) NULL
);

CREATE TABLE CM_MDB_MODEL_AUDIT (
 MODEL_ID NUMERIC(19) NULL,
 NOTE VARCHAR(255) NULL,
 TIMESTAMP DATETIME NULL
);


ALTER TABLE CMT_OABA_BATCHJOB_AUDIT ADD CONSTRAINT CMTBBTCHJBAUDITBTCHJBD FOREIGN KEY (BATCHJOB_ID) REFERENCES CMT_OABA_BATCHJOB (ID);

ALTER TABLE CMT_TRANSITIVITYJOB_AUDIT ADD CONSTRAINT CMTTRNSTVTYTRNSTVTYJBD FOREIGN KEY (TRANSITIVITYJOB_ID) REFERENCES CMT_TRANSITIVITY_JOB (ID);

ALTER TABLE CM_MDB_MODEL_AUDIT ADD CONSTRAINT CMMDBMODELAUDITMODELID FOREIGN KEY (MODEL_ID) REFERENCES CM_MDB_MODEL (ID);

ALTER TABLE CM_MDB_MODEL_FEATURE ADD CONSTRAINT CMMDBMODELFEATUREMDLID FOREIGN KEY (MODEL_ID) REFERENCES CM_MDB_MODEL (ID);


INSERT INTO CMT_SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('CMT_MODEL', 0);

INSERT INTO CMT_SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('OABA_BATCHJOB', 0);

INSERT INTO CMT_SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('TRANSITIVITYJOB', 0);

