CREATE TABLE CM_MDB_MODEL (
 ID NUMERIC(19) NOT NULL,
 CLUESET_NAME VARCHAR(255) NULL,
 CLUESET_SIGNATURE VARCHAR(255) NULL,
 EVALUATOR_SIGNATURE VARCHAR(255) NULL,
 ML_TYPE VARCHAR(255) NULL,
 MODEL_NAME VARCHAR(255) NULL,
 MODEL_SIGNATURE VARCHAR(255) NULL,
 SCHEMA_NAME VARCHAR(255) NULL,
 SCHEMA_SIGNATURE VARCHAR(255) NULL,
 PRIMARY KEY (ID))
;

CREATE TABLE CM_MDB_MODEL_FEATURE (
 CLUE_NUMBER INTEGER NULL,
 NAME VARCHAR(255) NULL,
 FEATURE_TYPE VARCHAR(255) NULL,
 ML_TYPE VARCHAR(255) NULL,
 WEIGHT FLOAT(16) NULL,
 MODEL_ID NUMERIC(19) NULL)
;

CREATE TABLE CM_MDB_MODEL_PROPERTY (
 MODEL_ID NUMERIC(19) NULL,
 VALUE VARCHAR(255) NULL,
 NAME VARCHAR(255) NULL)
;

CREATE TABLE CM_MDB_MODEL_NOTE (
 MODEL_ID NUMERIC(19) NULL,
 NOTE VARCHAR(255) NULL,
 TIMESTAMP DATETIME NULL)
;

ALTER TABLE CM_MDB_MODEL_FEATURE ADD CONSTRAINT CMMDBMODELFEATUREMDLID FOREIGN KEY (MODEL_ID) REFERENCES CM_MDB_MODEL (ID);

ALTER TABLE CM_MDB_MODEL_PROPERTY ADD CONSTRAINT CMMDBMODELPROPERTYMDLD FOREIGN KEY (MODEL_ID) REFERENCES CM_MDB_MODEL (ID);

ALTER TABLE CM_MDB_MODEL_NOTE ADD CONSTRAINT CMMDBMODELNOTEMODEL_ID FOREIGN KEY (MODEL_ID) REFERENCES CM_MDB_MODEL (ID);

INSERT INTO CMT_SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('CMT_MODEL', 0);

