// Generated by ChoiceMaker. Do not edit.
package com.choicemaker.demo.simple_person_matching.gendata.gend.internal.Person;
import java.util.logging.*;
import java.util.*;
import java.io.*;
import com.choicemaker.cm.core.*;
import com.choicemaker.cm.core.base.*;
import com.choicemaker.cm.core.util.*;
import com.choicemaker.cm.io.xml.base.*;
import com.choicemaker.util.*;
import com.choicemaker.demo.simple_person_matching.gendata.gend.internal.Person.*;
import java.util.Date;
import com.choicemaker.util.StringUtils;
public final class PersonXmlReporter implements XmlRecordOutputter {
private static Logger logger = Logger.getLogger(com.choicemaker.demo.simple_person_matching.gendata.gend.internal.Person.PersonXmlReporter.class.getName());
public void put(Writer w, Record r) throws IOException {
}
}
