CREATE TABLE CMT_OABA_BATCHJOB (
 ID NUMERIC(19) NOT NULL,
 TYPE VARCHAR(31) NULL,
 BPARAMS_ID NUMERIC(19) NULL,
 BPARENT_ID NUMERIC(19) NULL,
 DESCRIPTION VARCHAR(255) NULL,
 EXTERNAL_ID VARCHAR(255) NULL,
 FRACTION_COMPLETE INTEGER NULL,
 STATUS VARCHAR(255) NULL,
 TRANSACTION_ID NUMERIC(19) NULL,
 URM_ID NUMERIC(19) NULL,
 PRIMARY KEY (ID)
);

CREATE TABLE CMT_OABA_BATCH_PARAMS (
 ID NUMERIC(19) NOT NULL,
 HIGH_THRESHOLD FLOAT(16) NULL,
 LOW_THRESHOLD FLOAT(16) NULL,
 MASTER_MODEL VARCHAR(255) NULL,
 MASTER_RS IMAGE NULL,
 MAX_SINGLE INTEGER NULL,
 STAGE_MODEL VARCHAR(255) NULL,
 STAGE_RS IMAGE NULL,
 TRANSIVITIY BIT default 0 NULL,
 PRIMARY KEY (ID)
);

CREATE TABLE CMT_OABA_PROCESSING (
 ID NUMERIC(19) NOT NULL,
 EVENT_ID INTEGER NULL,
 INFO VARCHAR(255) NULL,
 JOB_ID NUMERIC(19) NULL,
 TIMESTAMP DATETIME NULL,
 JOB_TYPE VARCHAR(255) NULL,
 VERSION NUMERIC(19) NULL,
 PRIMARY KEY (ID)
);

CREATE TABLE CMT_SERVER_CONFIG (
 ID NUMERIC(19) NOT NULL,
 FILE_URI VARCHAR(255) NULL,
 HOST_NAME VARCHAR(255) NULL,
 MAX_CHUNK_COUNT INTEGER NULL,
 MAX_CHUNK_SIZE INTEGER NULL,
 MAX_THREADS INTEGER NULL,
 CONFIG_NAME VARCHAR(255) NULL,
 UUID VARCHAR(255) NULL,
 PRIMARY KEY (ID)
);

CREATE TABLE CMT_DEFAULT_SERVER_CONFIG (
 HOST_NAME VARCHAR(255) NOT NULL,
 SERVER_CONFIG NUMERIC(19) NULL,
 PRIMARY KEY (HOST_NAME)
);

CREATE TABLE CMT_OABA_BATCHJOB_AUDIT (
 BATCHJOB_ID NUMERIC(19) NULL,
 STATUS VARCHAR(255) NULL,
 TIMESTAMP DATETIME NULL
);

ALTER TABLE CMT_OABA_BATCHJOB_AUDIT
 ADD CONSTRAINT CMTBBTCHJBAUDITBTCHJBD
 FOREIGN KEY (BATCHJOB_ID)
 REFERENCES CMT_OABA_BATCHJOB (ID);

CREATE TABLE CMT_SEQUENCE (
 SEQ_NAME VARCHAR(50) NOT NULL,
 SEQ_COUNT NUMERIC(28) NULL,
 PRIMARY KEY (SEQ_NAME)
);

INSERT INTO CMT_SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('OABA_PROCESSING', 0);

INSERT INTO CMT_SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('OABA_BATCHJOB', 0);

INSERT INTO CMT_SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('OABA_BATCHPARAMS', 0);

INSERT INTO CMT_SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('SERVER_CONFIG', 0);

