CREATE TABLE CMT_OABA_BATCHJOB (
 ID NUMERIC(19) NOT NULL,
 TYPE VARCHAR(31) NULL,
 BPARENT_ID NUMERIC(19) NULL,
 DESCRIPTION VARCHAR(255) NULL,
 EXTERNAL_ID VARCHAR(255) NULL,
 PARAMS_ID NUMERIC(19) NULL,
 RIGOR CHAR(1) NULL,
 SERVER_ID NUMERIC(19) NULL,
 SETTINGS_ID NUMERIC(19) NULL,
 STATUS VARCHAR(255) NULL,
 TRANSACTION_ID NUMERIC(19) NULL,
 URM_ID NUMERIC(19) NULL,
 WORKING_DIR VARCHAR(255) NULL,
 PRIMARY KEY (ID)
);

CREATE TABLE CMT_OABA_BATCH_PROCESSING (
 ID NUMERIC(19) NOT NULL,
 EVENT_TYPE VARCHAR(31) NULL,
 EVENT_INFO VARCHAR(255) NULL,
 EVENT_NAME VARCHAR(255) NULL,
 EVENT_SEQNUM INTEGER NULL,
 TIMESTAMP DATETIME NULL,
 FRACTION_COMPLETE FLOAT(16) NULL,
 JOB_ID NUMERIC(19) NULL,
 PRIMARY KEY (ID)
);

CREATE TABLE CMT_OPERATION_PROPERTY (
 ID NUMERIC(19) NOT NULL,
 JOB_ID NUMERIC(19) NULL,
 NAME VARCHAR(255) NULL,
 VALUE VARCHAR(255) NULL,
 PRIMARY KEY (ID)
);

CREATE TABLE CMT_ABA_SETTINGS (
 ID NUMERIC(19) NOT NULL,
 TYPE VARCHAR(31) NULL,
 LIMIT_BLOCKSET INTEGER NULL,
 LIMIT_SINGLESET INTEGER NULL,
 LIMIT_SINGLETABLE INTEGER NULL,
 INTERVAL INTEGER NULL,
 MAX_BLOCKSIZE INTEGER NULL,
 MAX_CHUNKSIZE INTEGER NULL,
 MAX_MATCHES INTEGER NULL,
 MAX_OVERSIZE INTEGER NULL,
 MAX_SINGLE INTEGER NULL,
 MIN_FIELDS INTEGER NULL,
 PRIMARY KEY (ID)
);

CREATE TABLE CMT_RECORD_ID (
 ID NUMERIC(19) NOT NULL,
 TYPE CHAR(1) NULL,
 JOB_ID NUMERIC(19) NULL,
 RECORD_ID VARCHAR(255) NULL,
 SOURCE CHAR(1) NULL,
 TRANSLATED_ID INTEGER NULL,
 PRIMARY KEY (ID)
);

CREATE TABLE CMT_RECORD_SOURCE (
 ID NUMERIC(19) NOT NULL,
 TYPE VARCHAR(31) NULL,
 PRIMARY KEY (ID)
);

CREATE TABLE CMT_DEFAULT_SERVER_CONFIG (
 HOST_NAME VARCHAR(255) NOT NULL,
 SERVER_CONFIG NUMERIC(19) NULL,
 PRIMARY KEY (HOST_NAME)
);

CREATE TABLE CMT_DEFAULT_SETTINGS (
 SETTINGS_ID NUMERIC(19) NULL,
 MODEL VARCHAR(255) NOT NULL,
 BLOCKING_CONFIG VARCHAR(255) NOT NULL,
 DATABASE_CONFIG VARCHAR(255) NOT NULL,
 TYPE VARCHAR(255) NOT NULL,
 PRIMARY KEY (MODEL, BLOCKING_CONFIG, DATABASE_CONFIG, TYPE)
);

CREATE TABLE CMT_OABA_BATCH_PARAMS (
 ID NUMERIC(19) NOT NULL,
 FORMAT VARCHAR(255) NULL,
 GRAPH VARCHAR(255) NULL,
 HIGH_THRESHOLD FLOAT(16) NULL,
 LOW_THRESHOLD FLOAT(16) NULL,
 MASTER_ID NUMERIC(19) NULL,
 MASTER_TYPE VARCHAR(255) NULL,
 MODEL VARCHAR(255) NULL,
 STAGE_ID NUMERIC(19) NULL,
 STAGE_TYPE VARCHAR(255) NULL,
 TASK VARCHAR(255) NULL,
 TYPE VARCHAR(255) NULL,
 PRIMARY KEY (ID)
);

CREATE TABLE CMT_SERVER_CONFIG (
 ID NUMERIC(19) NOT NULL,
 FILE_URI VARCHAR(255) NULL,
 HOST_NAME VARCHAR(255) NULL,
 MAX_CHUNK_COUNT INTEGER NULL,
 MAX_CHUNK_SIZE INTEGER NULL,
 MAX_THREADS INTEGER NULL,
 CONFIG_NAME VARCHAR(255) NULL,
 UUID VARCHAR(255) NULL,
 PRIMARY KEY (ID)
);

CREATE TABLE CMT_SQL_RECORDSOURCE (
 ID NUMERIC(19) NOT NULL,
 CLASS VARCHAR(255) NULL,
 DATA_SOURCE VARCHAR(255) NULL,
 DBCONFIG VARCHAR(255) NULL,
 MODEL VARCHAR(255) NULL,
 SQL VARCHAR(255) NULL,
 PRIMARY KEY (ID)
);

CREATE TABLE CMT_OABA_BATCHJOB_AUDIT (
 BATCHJOB_ID NUMERIC(19) NULL,
 STATUS VARCHAR(255) NULL,
 TIMESTAMP DATETIME NULL
);

ALTER TABLE CMT_SQL_RECORDSOURCE ADD CONSTRAINT CMT_SQL_RECORDSOURCEID FOREIGN KEY (ID) REFERENCES CMT_RECORD_SOURCE (ID);

ALTER TABLE CMT_OABA_BATCHJOB_AUDIT ADD CONSTRAINT CMTBBTCHJBAUDITBTCHJBD FOREIGN KEY (BATCHJOB_ID) REFERENCES CMT_OABA_BATCHJOB (ID);

CREATE TABLE CMT_SEQUENCE (
 SEQ_NAME VARCHAR(50) NOT NULL,
 SEQ_COUNT NUMERIC(28) NULL,
 PRIMARY KEY (SEQ_NAME)
);

INSERT INTO CMT_SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('ABA_SETTINGS', 0);

INSERT INTO CMT_SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('OABA_BATCHPARAMS', 0);

INSERT INTO CMT_SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('SERVER_CONFIG', 0);

INSERT INTO CMT_SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('OP_PROP', 0);

INSERT INTO CMT_SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('TRANSLATED_ID', 0);

INSERT INTO CMT_SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('BATCHPROCESSING', 0);

INSERT INTO CMT_SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('RECORD_SOURCE_ROLE', 0);

INSERT INTO CMT_SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('BATCHJOB', 0);

