// Generated by ChoiceMaker. Do not edit.
package com.choicemaker.demo.simple_person_matching.gendata.gend.Person2;
import java.util.Date;
import com.choicemaker.util.StringUtils;
import com.choicemaker.cm.validation.eclipse.impl.Validators;
/**
 * Generated holder class for the node type person. See package documentation for details.
 */
public class PersonRecordHolder implements com.choicemaker.demo.simple_person_matching.gendata.gend.Person2.IPersonRecordHolder, java.io.Serializable {
/** Default constructor. Initializes all all arrays for nested record to zero length arrays and all other values to their defaults (0/null). */public PersonRecordHolder() {
}
public void accept(com.choicemaker.cm.urm.base.IRecordVisitor ext){	ext.visit((com.choicemaker.cm.urm.base.IRecordHolder)this); }
private boolean linkage_roleValid;
protected String linkage_role;
/**
 * Returns whether the value of the field linkage_role is valid according to the validity predicate in the ChoiceMaker schema.
 * @return  Whether the value of the field linkage_role is valid according to the validity predicate in the ChoiceMaker schema.
*/
public boolean isLinkage_roleValid() {
return linkage_roleValid;
}
/**
 * Returns the value of linkage_role.
 * @return  The value of linkage_role.
*/
public String getLinkage_role() {
return linkage_role;
}
/**
 * Sets the value of linkage_role.
 * @param  __v  The value of linkage_role.
*/
public void setLinkage_role(String __v) {
this.linkage_role = __v;
}
private boolean entityIdValid;
protected int entityId;
/**
 * Returns whether the value of the field entityId is valid according to the validity predicate in the ChoiceMaker schema.
 * @return  Whether the value of the field entityId is valid according to the validity predicate in the ChoiceMaker schema.
*/
public boolean isEntityIdValid() {
return entityIdValid;
}
/**
 * Returns the value of entityId.
 * @return  The value of entityId.
*/
public int getEntityId() {
return entityId;
}
/**
 * Sets the value of entityId.
 * @param  __v  The value of entityId.
*/
public void setEntityId(int __v) {
this.entityId = __v;
}
private boolean recordIdValid;
protected int recordId;
/**
 * Returns whether the value of the field recordId is valid according to the validity predicate in the ChoiceMaker schema.
 * @return  Whether the value of the field recordId is valid according to the validity predicate in the ChoiceMaker schema.
*/
public boolean isRecordIdValid() {
return recordIdValid;
}
/**
 * Returns the value of recordId.
 * @return  The value of recordId.
*/
public int getRecordId() {
return recordId;
}
/**
 * Sets the value of recordId.
 * @param  __v  The value of recordId.
*/
public void setRecordId(int __v) {
this.recordId = __v;
}
private boolean ssnValid;
protected String ssn;
/**
 * Returns whether the value of the field ssn is valid according to the validity predicate in the ChoiceMaker schema.
 * @return  Whether the value of the field ssn is valid according to the validity predicate in the ChoiceMaker schema.
*/
public boolean isSsnValid() {
return ssnValid;
}
/**
 * Returns the value of ssn.
 * @return  The value of ssn.
*/
public String getSsn() {
return ssn;
}
/**
 * Sets the value of ssn.
 * @param  __v  The value of ssn.
*/
public void setSsn(String __v) {
this.ssn = __v;
}
private boolean firstNameValid;
protected String firstName;
/**
 * Returns whether the value of the field firstName is valid according to the validity predicate in the ChoiceMaker schema.
 * @return  Whether the value of the field firstName is valid according to the validity predicate in the ChoiceMaker schema.
*/
public boolean isFirstNameValid() {
return firstNameValid;
}
/**
 * Returns the value of firstName.
 * @return  The value of firstName.
*/
public String getFirstName() {
return firstName;
}
/**
 * Sets the value of firstName.
 * @param  __v  The value of firstName.
*/
public void setFirstName(String __v) {
this.firstName = __v;
}
private boolean middleNameValid;
protected String middleName;
/**
 * Returns whether the value of the field middleName is valid according to the validity predicate in the ChoiceMaker schema.
 * @return  Whether the value of the field middleName is valid according to the validity predicate in the ChoiceMaker schema.
*/
public boolean isMiddleNameValid() {
return middleNameValid;
}
/**
 * Returns the value of middleName.
 * @return  The value of middleName.
*/
public String getMiddleName() {
return middleName;
}
/**
 * Sets the value of middleName.
 * @param  __v  The value of middleName.
*/
public void setMiddleName(String __v) {
this.middleName = __v;
}
private boolean lastNameValid;
protected String lastName;
/**
 * Returns whether the value of the field lastName is valid according to the validity predicate in the ChoiceMaker schema.
 * @return  Whether the value of the field lastName is valid according to the validity predicate in the ChoiceMaker schema.
*/
public boolean isLastNameValid() {
return lastNameValid;
}
/**
 * Returns the value of lastName.
 * @return  The value of lastName.
*/
public String getLastName() {
return lastName;
}
/**
 * Sets the value of lastName.
 * @param  __v  The value of lastName.
*/
public void setLastName(String __v) {
this.lastName = __v;
}
private boolean streetNumberValid;
protected String streetNumber;
/**
 * Returns whether the value of the field streetNumber is valid according to the validity predicate in the ChoiceMaker schema.
 * @return  Whether the value of the field streetNumber is valid according to the validity predicate in the ChoiceMaker schema.
*/
public boolean isStreetNumberValid() {
return streetNumberValid;
}
/**
 * Returns the value of streetNumber.
 * @return  The value of streetNumber.
*/
public String getStreetNumber() {
return streetNumber;
}
/**
 * Sets the value of streetNumber.
 * @param  __v  The value of streetNumber.
*/
public void setStreetNumber(String __v) {
this.streetNumber = __v;
}
private boolean streetNameValid;
protected String streetName;
/**
 * Returns whether the value of the field streetName is valid according to the validity predicate in the ChoiceMaker schema.
 * @return  Whether the value of the field streetName is valid according to the validity predicate in the ChoiceMaker schema.
*/
public boolean isStreetNameValid() {
return streetNameValid;
}
/**
 * Returns the value of streetName.
 * @return  The value of streetName.
*/
public String getStreetName() {
return streetName;
}
/**
 * Sets the value of streetName.
 * @param  __v  The value of streetName.
*/
public void setStreetName(String __v) {
this.streetName = __v;
}
private boolean apartmentNumberValid;
protected String apartmentNumber;
/**
 * Returns whether the value of the field apartmentNumber is valid according to the validity predicate in the ChoiceMaker schema.
 * @return  Whether the value of the field apartmentNumber is valid according to the validity predicate in the ChoiceMaker schema.
*/
public boolean isApartmentNumberValid() {
return apartmentNumberValid;
}
/**
 * Returns the value of apartmentNumber.
 * @return  The value of apartmentNumber.
*/
public String getApartmentNumber() {
return apartmentNumber;
}
/**
 * Sets the value of apartmentNumber.
 * @param  __v  The value of apartmentNumber.
*/
public void setApartmentNumber(String __v) {
this.apartmentNumber = __v;
}
private boolean cityValid;
protected String city;
/**
 * Returns whether the value of the field city is valid according to the validity predicate in the ChoiceMaker schema.
 * @return  Whether the value of the field city is valid according to the validity predicate in the ChoiceMaker schema.
*/
public boolean isCityValid() {
return cityValid;
}
/**
 * Returns the value of city.
 * @return  The value of city.
*/
public String getCity() {
return city;
}
/**
 * Sets the value of city.
 * @param  __v  The value of city.
*/
public void setCity(String __v) {
this.city = __v;
}
private boolean stateValid;
protected String state;
/**
 * Returns whether the value of the field state is valid according to the validity predicate in the ChoiceMaker schema.
 * @return  Whether the value of the field state is valid according to the validity predicate in the ChoiceMaker schema.
*/
public boolean isStateValid() {
return stateValid;
}
/**
 * Returns the value of state.
 * @return  The value of state.
*/
public String getState() {
return state;
}
/**
 * Sets the value of state.
 * @param  __v  The value of state.
*/
public void setState(String __v) {
this.state = __v;
}
private boolean zipValid;
protected String zip;
/**
 * Returns whether the value of the field zip is valid according to the validity predicate in the ChoiceMaker schema.
 * @return  Whether the value of the field zip is valid according to the validity predicate in the ChoiceMaker schema.
*/
public boolean isZipValid() {
return zipValid;
}
/**
 * Returns the value of zip.
 * @return  The value of zip.
*/
public String getZip() {
return zip;
}
/**
 * Sets the value of zip.
 * @param  __v  The value of zip.
*/
public void setZip(String __v) {
this.zip = __v;
}
/**
 * Returns the ID of the record holder. 
 * @return  Returns the ID of the node.
*/
public java.lang.Comparable getId() {
return new Integer(recordId);
}
/** Copy constructor. Performs a deep copy of the nodes, but not the values.
 * @param  __o  The node to copy.
*/
public PersonRecordHolder(PersonBase __o) {
linkage_role = __o.getLinkage_role();
linkage_roleValid = __o.isLinkage_roleValid();
entityId = __o.getEntityId();
entityIdValid = __o.isEntityIdValid();
recordId = __o.getRecordId();
recordIdValid = __o.isRecordIdValid();
ssn = __o.getSsn();
ssnValid = __o.isSsnValid();
firstName = __o.getFirstName();
firstNameValid = __o.isFirstNameValid();
middleName = __o.getMiddleName();
middleNameValid = __o.isMiddleNameValid();
lastName = __o.getLastName();
lastNameValid = __o.isLastNameValid();
streetNumber = __o.getStreetNumber();
streetNumberValid = __o.isStreetNumberValid();
streetName = __o.getStreetName();
streetNameValid = __o.isStreetNameValid();
apartmentNumber = __o.getApartmentNumber();
apartmentNumberValid = __o.isApartmentNumberValid();
city = __o.getCity();
cityValid = __o.isCityValid();
state = __o.getState();
stateValid = __o.isStateValid();
zip = __o.getZip();
zipValid = __o.isZipValid();
}
}
