// Generated by ChoiceMaker. Do not edit.
package com.choicemaker.demo.simple_person_matching.gendata.gend.Person2;
import java.util.Date;
import com.choicemaker.util.StringUtils;
import com.choicemaker.cm.validation.eclipse.impl.Validators;
/**
 * Generated base interface for the node type person. See package documentation for details.
 */
public interface PersonBase extends java.io.Serializable {
/**
 * Returns whether the value of the field linkage_role is valid according to the validity predicate in the ChoiceMaker schema.
 * @return  Whether the value of the field linkage_role is valid according to the validity predicate in the ChoiceMaker schema.
*/
public boolean isLinkage_roleValid();
/**
 * Returns the value of linkage_role.
 * @return  The value of linkage_role.
*/
public String getLinkage_role();
/**
 * Returns whether the value of the field entityId is valid according to the validity predicate in the ChoiceMaker schema.
 * @return  Whether the value of the field entityId is valid according to the validity predicate in the ChoiceMaker schema.
*/
public boolean isEntityIdValid();
/**
 * Returns the value of entityId.
 * @return  The value of entityId.
*/
public int getEntityId();
/**
 * Returns whether the value of the field recordId is valid according to the validity predicate in the ChoiceMaker schema.
 * @return  Whether the value of the field recordId is valid according to the validity predicate in the ChoiceMaker schema.
*/
public boolean isRecordIdValid();
/**
 * Returns the value of recordId.
 * @return  The value of recordId.
*/
public int getRecordId();
/**
 * Returns whether the value of the field ssn is valid according to the validity predicate in the ChoiceMaker schema.
 * @return  Whether the value of the field ssn is valid according to the validity predicate in the ChoiceMaker schema.
*/
public boolean isSsnValid();
/**
 * Returns the value of ssn.
 * @return  The value of ssn.
*/
public String getSsn();
/**
 * Returns whether the value of the field firstName is valid according to the validity predicate in the ChoiceMaker schema.
 * @return  Whether the value of the field firstName is valid according to the validity predicate in the ChoiceMaker schema.
*/
public boolean isFirstNameValid();
/**
 * Returns the value of firstName.
 * @return  The value of firstName.
*/
public String getFirstName();
/**
 * Returns whether the value of the field middleName is valid according to the validity predicate in the ChoiceMaker schema.
 * @return  Whether the value of the field middleName is valid according to the validity predicate in the ChoiceMaker schema.
*/
public boolean isMiddleNameValid();
/**
 * Returns the value of middleName.
 * @return  The value of middleName.
*/
public String getMiddleName();
/**
 * Returns whether the value of the field lastName is valid according to the validity predicate in the ChoiceMaker schema.
 * @return  Whether the value of the field lastName is valid according to the validity predicate in the ChoiceMaker schema.
*/
public boolean isLastNameValid();
/**
 * Returns the value of lastName.
 * @return  The value of lastName.
*/
public String getLastName();
/**
 * Returns whether the value of the field streetNumber is valid according to the validity predicate in the ChoiceMaker schema.
 * @return  Whether the value of the field streetNumber is valid according to the validity predicate in the ChoiceMaker schema.
*/
public boolean isStreetNumberValid();
/**
 * Returns the value of streetNumber.
 * @return  The value of streetNumber.
*/
public String getStreetNumber();
/**
 * Returns whether the value of the field streetName is valid according to the validity predicate in the ChoiceMaker schema.
 * @return  Whether the value of the field streetName is valid according to the validity predicate in the ChoiceMaker schema.
*/
public boolean isStreetNameValid();
/**
 * Returns the value of streetName.
 * @return  The value of streetName.
*/
public String getStreetName();
/**
 * Returns whether the value of the field apartmentNumber is valid according to the validity predicate in the ChoiceMaker schema.
 * @return  Whether the value of the field apartmentNumber is valid according to the validity predicate in the ChoiceMaker schema.
*/
public boolean isApartmentNumberValid();
/**
 * Returns the value of apartmentNumber.
 * @return  The value of apartmentNumber.
*/
public String getApartmentNumber();
/**
 * Returns whether the value of the field city is valid according to the validity predicate in the ChoiceMaker schema.
 * @return  Whether the value of the field city is valid according to the validity predicate in the ChoiceMaker schema.
*/
public boolean isCityValid();
/**
 * Returns the value of city.
 * @return  The value of city.
*/
public String getCity();
/**
 * Returns whether the value of the field state is valid according to the validity predicate in the ChoiceMaker schema.
 * @return  Whether the value of the field state is valid according to the validity predicate in the ChoiceMaker schema.
*/
public boolean isStateValid();
/**
 * Returns the value of state.
 * @return  The value of state.
*/
public String getState();
/**
 * Returns whether the value of the field zip is valid according to the validity predicate in the ChoiceMaker schema.
 * @return  Whether the value of the field zip is valid according to the validity predicate in the ChoiceMaker schema.
*/
public boolean isZipValid();
/**
 * Returns the value of zip.
 * @return  The value of zip.
*/
public String getZip();
}
