package com.choicemaker.fake;

import java.io.File;

import org.apache.maven.plugin.AbstractMojo;
import org.apache.maven.plugin.MojoExecutionException;
import org.apache.maven.plugins.annotations.Component;
import org.apache.maven.plugins.annotations.LifecyclePhase;
import org.apache.maven.plugins.annotations.Mojo;
import org.apache.maven.plugins.annotations.Parameter;
import org.apache.maven.project.MavenProject;

/**
 * Goal which generates Java source code from ClueMaker model files
 */
@Mojo(name = "compile", defaultPhase = LifecyclePhase.PROCESS_SOURCES )
public class MyMojo3 extends AbstractMojo {

	/**
	 * Default location, relative to the project build directory, for the root
	 * of the source code tree generated by this Maven plugin.
	 */
	private static final String GENERATED_SOURCE_PATH = MyMojo2.GENERATED_SOURCE_PATH;

	private static final String EOL = System.getProperty("line.separator");

	@Component
	private MavenProject project;

	/**
	 * A required location for generated Java files
	 */
	@Parameter(defaultValue = "${project.build.directory}/generated-sources/cluemaker",
			required = true)
	private File generatedSourceDirectory;

	/**
	 * A required location for compiled Java files
	 */
	@Parameter(defaultValue = "${project.build.outputDirectory}",
			required = true)
	private File compiledCodeDirectory;

	public void execute() throws MojoExecutionException {

//		// Set up the source and target directories
//		File f = generatedSourceDirectory;
//		if (!f.exists()) {
//			f.mkdirs();
//		}
//		getLog().debug("generatedSourceDirectory: " + generatedSourceDirectory);
//
//		// Add the generated-sources directory to the build path
//		project.addCompileSourceRoot(generatedSourceDirectory.getPath());
		
		if (getLog().isInfoEnabled()) {
			getLog().info("Compile source roots:");
			for (String s : project.getCompileSourceRoots()) {
				getLog().info(MyMojo2.SP2 + s);
			}
		}
	}

}
